export function getMessage() {
    return {
        "inline_actions:comment": "Post comments in ad",
        "inline_actions:like": "Page likes in ad",
        "inline_actions:link_click": "Link clicks in ad",
        "inline_actions:photo_view": "Photo views in ad",
        "inline_actions:post_like": "Post reactions in ad",
        "inline_actions:video_play": "Clicks to play video in ad",
        "none": "None",
        "adgroup_delivery": "Ad delivery",
        "attribution_setting": "Attribution setting",
        "bid": "Bid strategy",
        "budget": "Budget",
        "budget_goal": "Budget goal",
        "budget_type": "Budget Type",
        "budget_value": "Budget",
        "campaign_budget_type": "Ad set budget type",
        "campaign_budget_value": "Ad set budget",
        "campaign_delivery": "Ad set delivery",
        "campaign_group_budget_type": "Campaign budget type",
        "campaign_group_budget_value": "Campaign budget",
        "campaign_group_delivery": "Campaign delivery",
        "creative_summary": "Ad creative",
        "deal_end": "Deal end",
        "deal_start": "Deal start",
        "delivery": "Delivery",
        "delivery_end": "Ends",
        "delivery_info": "Delivery",
        "delivery_level": "Delivery level",
        "delivery_start": "Starts",
        "delivery_status": "Delivery status",
        "impressions_goal": "Impressions goal",
        "name": "Name",
        "pacing": "Pacing",
        "schedule": "Schedule",
        "start_time": "Starts",
        "stop_time": "Ends",
        "1d_click": "1-day click",
        "1d_view": "1-day view",
        "28d_click": "28-day click",
        "28d_view": "28-day view",
        "7d_click": "7-day click",
        "7d_view": "7-day view",
        "inline": "On ad",
        "1d_ev": "1-day engaged-view",
        "skan_view": "View, SKAdNetwork",
        "skan_click": "Click, SKAdNetwork",
        "account_currency": "Currency",
        "account_default_attribution_windows": "Default attribution windows",
        "account_id": "Account ID",
        "account_name": "Account name",
        "account_timezone": "Time zone",
        "actions_per_impression": "Actions per Impression",
        "action_canvas_component_id": "Canvas component ID",
        "action_canvas_component_name": "Instant Experience component",
        "action_device": "Conversion device",
        "action_event_channel": "Channel",
        "action_link_click_destination": "Link click destination",
        "action_location_code": "Location code",
        "action_reaction": "Post reaction type",
        "action_video_asset_id": "Video asset ID",
        "action_category": "Category",
        "action_brand": "Brand",
        "activity_recency": "Activity recency",
        "adgroup_bid_type": "Bid Type",
        "adgroup_bid_value": "Bid",
        "adgroup_id": "Ad ID",
        "adgroup_name": "Ad name",
        "ad_creative_link_url": "Ad creative link URL",
        "ad_format_asset": "Ad format",
        "age": "Age",
        "app_store_clicks": "App Store Clicks",
        "attention_events_per_impression": "Attention Impressions Rate",
        "attention_events_unq_per_reach": "Unique Attention Impressions Rate",
        "auction_bid": "Auction bid",
        "auction_max_competitor_bid": "Auction competition change",
        "business_contact_option_clicks": "Orders initiated",
        "business_image_clicks": "Menu clicks",
        "marketing_messages_sent": "Sent",
        "marketing_messages_delivered": "Received",
        "marketing_messages_read_rate": "Read rate",
        "marketing_messages_link_btn_click": "Link clicks",
        "marketing_messages_language": "Language",
        "wish_bid": "Auction competition index",
        "auction_competitiveness": "Auction competition",
        "impressions_auto_refresh": "Auto-refresh impressions",
        "body_asset": "Text",
        "buying_type": "Buying type",
        "call_to_action_asset": "Call to Action",
        "call_to_action_clicks": "Button clicks",
        "campaign_bid_type": "Bid Type",
        "campaign_bid_value": "Bid",
        "campaign_group_end": "Ends",
        "campaign_end": "Ends",
        "campaign_group_id": "Campaign ID",
        "campaign_group_name": "Campaign name",
        "campaign_group_start": "Starts",
        "campaign_id": "Ad set ID",
        "campaign_name": "Ad set name",
        "campaign_start": "Starts",
        "canvas_avg_view_percent": "Instant Experience view percentage",
        "canvas_avg_view_percentage_per_component": "Avg. view % per Canvas component",
        "canvas_avg_view_time": "Instant Experience view time",
        "card_views": "Card views",
        "action_carousel_card_id": "Carousel card ID",
        "action_carousel_card_name": "Carousel card",
        "catalog_segment_actions:omni_purchase": "Purchases with shared items",
        "catalog_segment_actions:offline_conversion.purchase": "Offline purchases with shared items",
        "catalog_segment_actions:app_custom_event.fb_mobile_purchase": "Mobile app purchases with shared items",
        "catalog_segment_actions:offsite_conversion.fb_pixel_purchase": "Website purchases with shared items",
        "catalog_segment_actions:omni_add_to_cart": "Adds to cart with shared items",
        "catalog_segment_actions:app_custom_event.fb_mobile_add_to_cart": "Mobile app adds to cart with shared items",
        "catalog_segment_actions:offsite_conversion.fb_pixel_add_to_cart": "Website adds to cart with shared items",
        "catalog_segment_actions:omni_view_content": "Content views with shared items",
        "catalog_segment_actions:app_custom_event.fb_mobile_content_view": "Mobile app content views with shared items",
        "catalog_segment_actions:offsite_conversion.fb_pixel_view_content": "Website content views with shared items",
        "catalog_segment_value:omni_add_to_cart": "Adds to cart conversion value for shared items only",
        "catalog_segment_value:omni_purchase": "Purchases conversion value for shared items only",
        "catalog_segment_value:app_custom_event": "Mobile app actions for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_achievement_unlocked": "Mobile app achievements unlocked for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_activate_app": "Mobile app sessions for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_add_payment_info": "Mobile app adds of payment info for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_add_to_cart": "Mobile app adds to cart conversion value for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_add_to_wishlist": "Mobile app adds to wishlist for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_complete_registration": "Mobile app registrations completed for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_content_view": "Mobile app content views for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_initiated_checkout": "Mobile app checkouts initiated for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_level_achieved": "Mobile app levels completed for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_purchase": "Mobile app purchases conversion value for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_rate": "Mobile app ratings submitted for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_search": "Mobile app searches for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_spent_credits": "Mobile app credits spent for shared items only",
        "catalog_segment_value:app_custom_event.fb_mobile_tutorial_completion": "Mobile app tutorials completed for shared items only",
        "catalog_segment_value:app_custom_event.other": "Other mobile app actions for shared items only",
        "catalog_segment_value:offline_conversion": "Offline action (all) for shared items only",
        "catalog_segment_value:offline_conversion.add_payment_info": "Offline adds of payment info for shared items only",
        "catalog_segment_value:offline_conversion.add_to_cart": "Offline adds to cart for shared items only",
        "catalog_segment_value:offline_conversion.add_to_wishlist": "Offline adds to wishlist for shared items only",
        "catalog_segment_value:offline_conversion.complete_registration": "Offline registrations completed for shared items only",
        "catalog_segment_value:offline_conversion.initiate_checkout": "Offline checkouts initiated for shared items only",
        "catalog_segment_value:offline_conversion.lead": "Offline leads for shared items only",
        "catalog_segment_value:offline_conversion.other": "Offline other for shared items only",
        "catalog_segment_value:offline_conversion.purchase": "Offline purchases conversion value for shared items only",
        "catalog_segment_value:offline_conversion.search": "Offline searches for shared items only",
        "catalog_segment_value:offline_conversion.view_content": "Offline content views for shared items only",
        "catalog_segment_value:offsite_conversion": "Website conversions for shared items only",
        "catalog_segment_value:offsite_conversion.add_to_cart": "Website adds to cart for shared items only (conversion-tracking pixel)",
        "catalog_segment_value:offsite_conversion.checkout": "Website checkouts for shared items only (conversion-tracking pixel)",
        "catalog_segment_value:offsite_conversion.fb_pixel_add_payment_info": "Website adds of payment info for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_add_to_cart": "Website adds to cart conversion value for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_add_to_wishlist": "Website adds to wishlist for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_complete_registration": "Website registrations completed for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_initiate_checkout": "Website checkouts initiated for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_lead": "Website leads for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_purchase": "Website purchases conversion value for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_search": "Website searches for shared items only",
        "catalog_segment_value:offsite_conversion.fb_pixel_view_content": "Website content views for shared items only",
        "catalog_segment_value:offsite_conversion.lead": "Website leads (conversion-tracking pixel) for shared items only",
        "catalog_segment_value:offsite_conversion.other": "Other website (conversion-tracking pixel) for shared items only",
        "catalog_segment_value:offsite_conversion.registration": "Website registrations (conversion-tracking pixel) for shared items only",
        "catalog_segment_value_mobile_purchase_roas:app_custom_event.fb_mobile_purchase": "Mobile app purchase ROAS for shared items only",
        "catalog_segment_value_omni_purchase_roas:omni_purchase": "Purchase ROAS for shared items only",
        "catalog_segment_value_website_purchase_roas:offsite_conversion.fb_pixel_purchase": "Website purchase ROAS for shared items only",
        "promoted_product_set_value:omni_purchase": "Purchase conversion value for promoted product set",
        "converted_product_value:offsite_conversion.fb_pixel_purchase": "Website purchases converted product value",
        "converted_product_value:app_custom_event.fb_mobile_purchase": "Mobile purchases converted product value",
        "converted_product_value:offline_conversion.purchase": "Offline purchases converted product value",
        "converted_product_quantity:offsite_conversion.fb_pixel_purchase": "Website purchases converted product quantity",
        "converted_product_quantity:app_custom_event.fb_mobile_purchase": "Mobile purchases converted product quantity",
        "converted_product_quantity:offline_conversion.purchase": "Offline purchases converted product quantity",
        "clicks": "Clicks (all)",
        "conversion_window": "Conversion window",
        "last_significant_edit": "Last significant edit",
        "campaign_insights": "Insights",
        "cost_per_action_result": "Cost per Action Result",
        "cost_per_dda_countby_convs": "Cost per incremental result",
        "cost_per_estimated_ad_recallers": "Cost per estimated ad recall lift (people)",
        "cost_per_inline_link_click": "Cost per Inline Link Click",
        "cost_per_inline_post_engagement": "Cost per Inline Post Engagement",
        "cost_per_objective_result": "Cost per results",
        "cost_per_optimization_result": "Cost per optimisation event",
        "cost_per_result": "Cost per result",
        "cost_per_store_visit": "Cost per store visit",
        "cost_per_store_visit_action": "Cost per store visit",
        "cost_per_total_action": "Cost per any action",
        "cost_per_unique_click": "Cost per unique click (all)",
        "cost_per_unique_inline_link_click": "Cost per Unique Inline Link Click",
        "country": "Country",
        "cpc": "CPC (all)",
        "cpm": "CPM (cost per 1,000 impressions)",
        "cpp": "Cost per 1,000 Accounts Centre accounts reached",
        "creative_fingerprint": "Creative fingerprint",
        "creative_name": "Ads",
        "creative_delivery_info": "Delivery",
        "ctr": "CTR (all)",
        "cumulative_reach": "Reach (lifetime)",
        "lifetime_frequency": "Frequency (lifetime)",
        "weighted_ad_lifetime_frequency": "Weighted ad frequency (lifetime)",
        "date_start": "Reporting starts",
        "date_stop": "Reporting ends",
        "dda_countby_convs": "Incremental results",
        "days_1": "Day",
        "days_7": "Week",
        "days_14": "2 weeks",
        "monthly": "Month",
        "deduping_1st_source_ad": "Most overlapping ad set",
        "deduping_1st_source_ratio": "Auction removal for most overlapping ad set",
        "deduping_2nd_source_ad": "Second-most overlapping ad set",
        "deduping_2nd_source_ratio": "Auction removal for second-most overlapping ad set",
        "deduping_3rd_source_ad": "Third-most overlapping ad set",
        "deduping_3rd_source_ratio": "Auction removal for third-most overlapping ad set",
        "deduping_ratio": "Auction overlap rate",
        "deeplink_clicks": "Deep Link Clicks",
        "description_asset": "Description",
        "action_destination": "Destination",
        "device_platform": "Device platform",
        "dma": "DMA",
        "dwell_3_sec": "3-second dwells",
        "dwell_5_sec": "Five-second dwells",
        "dwell_7_sec": "Seven-second dwells",
        "cost_per_dwell_3_sec": "Cost per 1,000 3-second dwells",
        "cost_per_dwell_5_sec": "Cost per 1,000 5-second dwells",
        "cost_per_dwell_7_sec": "Cost per 1,000 7-second dwells",
        "thumb_stops": "Dwell",
        "cost_per_dwell": "Cost per 1,000 dwells",
        "dwell_rate": "Dwell rate",
        "estimated_ad_recallers": "Estimated ad recall lift (people)",
        "estimated_ad_recallers_lower_bound": "Estimated ad recallers lower boundary",
        "estimated_ad_recallers_upper_bound": "Estimated ad recallers upper boundary",
        "estimated_ad_recall_rate": "Estimated ad recall lift rate",
        "estimated_ad_recall_rate_lower_bound": "Estimated ad recall rate lower boundary",
        "estimated_ad_recall_rate_upper_bound": "Estimated as recall Rate upper boundary",
        "frequency": "Frequency",
        "frequency_value": "Frequency distribution",
        "gender": "Gender",
        "high_cpa_spend_alert": "High CPA spent alert",
        "hourly_stats_aggregated_by_advertiser_time_zone": "Time of day (ad account time zone)",
        "hourly_stats_aggregated_by_audience_time_zone": "Time of day (viewer's time zone)",
        "impressions_gross": "Gross impressions (includes invalid impressions from non-human traffic)",
        "image_asset": "Image",
        "impressions": "Impressions",
        "impression_device": "Impression device",
        "inline_link_clicks": "Inline link clicks in ad",
        "inline_link_click_ctr": "Inline Link CTR",
        "inline_post_engagement": "Inline post engagement in ad",
        "kpi_results": "KPI results",
        "link_url_asset": "Website URL",
        "media_asset": "Image, video and slideshow",
        "creative_media_type": "Media type",
        "new_reach": "New reach",
        "objective": "Objective",
        "objective_results": "Results",
        "objective_result_rate": "Result rate",
        "optimization_goal": "Optimisation Goal",
        "optimization_results": "Optimisation events",
        "percentage_audience_reached": "Audience reached ratio",
        "percentage_first_time_impressions": "First-time impression ratio",
        "performance_indicator": "Result Type",
        "placement": "Placement",
        "place_page_id": "Business locations",
        "place_page_name": "Business name",
        "platform_position": "Placement",
        "product_id": "Product ID",
        "product_item_id": "Product ID",
        "product_set_id": "Product set ID",
        "publisher_platform": "Platform",
        "quality_score_ectr": "Engagement rate ranking",
        "quality_score_ecvr": "Conversion rate ranking",
        "quality_score_organic": "Quality ranking",
        "quality_ranking": "Quality ranking",
        "engagement_rate_ranking": "Engagement rate ranking",
        "conversion_rate_ranking": "Conversion rate ranking",
        "reach": "Reach",
        "region": "Region",
        "region_id": "Region ID",
        "relevance_score": "Ad relevance score",
        "results": "Results",
        "results_share": "Results share",
        "result_rate": "Result rate",
        "rule_asset": "Target spec ID",
        "social_clicks": "Social clicks (all)",
        "social_impressions": "Social impressions",
        "social_reach": "Social reach",
        "spend": "Amount spent",
        "store_visits": "Store visits",
        "store_visit_actions": "Store visits",
        "title_asset": "Headline (ad settings)",
        "today_spend": "Amount spent today",
        "total_actions": "Actions",
        "total_action_value": "Conversion value",
        "total_unique_actions": "People taking action",
        "unique_clicks": "Unique clicks (all)",
        "unique_ctr": "Unique CTR (all)",
        "unique_inline_link_clicks": "Unique inline link clicks in ad",
        "unique_inline_link_click_ctr": "Unique Inline Link CTR",
        "unique_link_clicks_ctr": "Unique CTR (link click-through rate)",
        "unique_social_clicks": "Unique social clicks (all)",
        "unique_social_impressions": "Unique social impressions",
        "video_asset": "Video",
        "action_video_type": "Video view type",
        "website_clicks": "Link clicks",
        "website_ctr": "Website CTR",
        "actions:like": "Page Likes",
        "actions:app_custom_event": "Mobile app actions",
        "actions:app_custom_event.fb_mobile_achievement_unlocked": "Mobile app achievements unlocked",
        "actions:app_custom_event.fb_mobile_activate_app": "Mobile app sessions",
        "actions:app_custom_event.fb_mobile_add_payment_info": "Mobile app payment info adds",
        "actions:app_custom_event.fb_mobile_add_to_cart": "Mobile app adds to cart",
        "actions:app_custom_event.fb_mobile_add_to_wishlist": "Mobile app adds to wishlist",
        "actions:app_custom_event.fb_mobile_complete_registration": "Mobile app registrations completed",
        "actions:app_custom_event.fb_mobile_content_view": "Mobile app content views",
        "actions:app_custom_event.fb_mobile_d2_retention": "Mobile app day 2 retention",
        "actions:app_custom_event.fb_mobile_d7_retention": "Mobile app day 7 retention",
        "actions:app_custom_event.fb_mobile_initiated_checkout": "Mobile app checkouts initiated",
        "actions:app_custom_event.fb_mobile_level_achieved": "Mobile app levels completed",
        "actions:app_custom_event.fb_mobile_purchase": "Mobile app purchases",
        "actions:app_custom_event.fb_mobile_rate": "Mobile app ratings submitted",
        "actions:app_custom_event.fb_mobile_search": "Mobile app searches",
        "actions:app_custom_event.fb_mobile_spent_credits": "Mobile app credits spent",
        "actions:app_custom_event.fb_mobile_tutorial_completion": "Mobile app tutorials completed",
        "actions:app_custom_event.other": "Other mobile app actions",
        "actions:app_engagement": "Desktop app engagements",
        "actions:app_install": "Desktop app installs",
        "actions:app_story": "Desktop app story engagements",
        "actions:app_use": "Desktop app uses",
        "actions:attention_event": "Attention Impressions",
        "actions:checkin": "Check-ins",
        "actions:commerce_event": "Commerce actions",
        "actions:commerce_event.add_to_cart": "Adds to cart (commerce)",
        "actions:commerce_event.message_to_buy": "Messages to buy (commerce)",
        "actions:commerce_event.other": "Other commerce actions",
        "actions:commerce_event.purchase": "Purchases (commerce)",
        "actions:commerce_event.view_content": "Product views (commerce)",
        "actions:receive_offer": "Offers saved",
        "actions:credit_spent": "Desktop app credit spends",
        "actions:dwell": "Post dwells",
        "actions:follow": "Question follows",
        "actions:games.plays": "Game plays",
        "actions:gift_sale": "Gift sales",
        "actions:landing_page_view": "Landing page views",
        "actions:leadgen.other": "Leads (form)",
        "actions:leadgen_grouped": "Leads (form)",
        "actions:contact": "Website contacts",
        "actions:donate": "Website donations",
        "actions:find_location": "Website location searches",
        "actions:customize_product": "Website products customised",
        "actions:start_trial": "Website trials started",
        "actions:subscribe": "Website subscriptions",
        "actions:schedule": "Website appointments scheduled",
        "actions:submit_application": "Website applications submitted",
        "actions:contact_mobile_app": "Mobile app contacts",
        "actions:donate_mobile_app": "Mobile app donations",
        "actions:find_location_mobile_app": "Mobile app location searches",
        "actions:customize_product_mobile_app": "Mobile app products customised",
        "actions:start_trial_mobile_app": "Mobile app trials started",
        "actions:subscribe_mobile_app": "Mobile app subscriptions",
        "actions:schedule_mobile_app": "Mobile app appointments scheduled",
        "actions:submit_application_mobile_app": "Mobile app applications submitted",
        "actions:link_click": "Link clicks",
        "actions:mention": "Page mentions",
        "actions:messenger.block": "New blocked messaging contacts",
        "actions:messenger.reply": "Messaging replies",
        "actions:offsite_mobile_app_conversion": "Mobile App Event",
        "actions:mobile_app_install": "Mobile app installs",
        "actions:new_mobile": "Newly Purchased Mobile Devices",
        "actions:offline_conversion": "Offline Actions (All)",
        "actions:offline_conversion.add_payment_info": "Offline adds of payment info",
        "actions:offline_conversion.add_to_cart": "Offline adds to cart",
        "actions:offline_conversion.add_to_wishlist": "Offline adds to wishlist",
        "actions:offline_conversion.complete_registration": "Offline registrations completed",
        "actions:offline_conversion.initiate_checkout": "Offline checkouts initiated",
        "actions:offline_conversion.lead": "Offline leads",
        "actions:offline_conversion.other": "Other offline conversions",
        "actions:offline_conversion.purchase": "Offline purchases",
        "actions:offline_conversion.search": "Offline searches",
        "actions:offline_conversion.view_content": "Offline content views",
        "actions:offsite_conversion": "Website conversions",
        "actions:offsite_conversion.add_to_cart": "Website adds to cart (conversion-tracking pixel)",
        "actions:offsite_conversion.checkout": "Website checkouts (conversion-tracking pixel)",
        "actions:offsite_conversion.fb_pixel_add_payment_info": "Website payment info adds",
        "actions:offsite_conversion.fb_pixel_add_to_cart": "Website adds to cart",
        "actions:offsite_conversion.fb_pixel_add_to_wishlist": "Website adds to wishlist",
        "actions:offsite_conversion.fb_pixel_complete_registration": "Website registrations completed",
        "actions:offsite_conversion.fb_pixel_initiate_checkout": "Website checkouts initiated",
        "actions:offsite_conversion.fb_pixel_lead": "Website leads",
        "actions:offsite_conversion.fb_pixel_purchase": "Website purchases",
        "actions:offsite_conversion.fb_pixel_search": "Website searches",
        "actions:offsite_conversion.fb_pixel_view_content": "Website content views",
        "actions:offsite_conversion.key_page_view": "Website key page views (conversion-tracking pixel)",
        "actions:offsite_conversion.lead": "Website leads (conversion-tracking pixel)",
        "actions:offsite_conversion.other": "Other website conversions (conversion-tracking pixel)",
        "actions:offsite_conversion.registration": "Website registrations (conversion-tracking pixel)",
        "actions:onsite_conversion.add_to_cart": "Meta add to cart",
        "actions:onsite_conversion.flow_complete": "Meta workflow completions",
        "actions:onsite_conversion.message_to_buy": "Meta message to buy",
        "actions:onsite_conversion.referral_sender_invites_sent": "Referral invitations",
        "actions:onsite_conversion.referral_sender_message_sent": "Referral invitation messages",
        "actions:onsite_conversion.messaging_block": "Blocked messaging contacts",
        "actions:onsite_conversion.messaging_first_reply": "New messaging contacts",
        "actions:onsite_conversion.messaging_reply": "Messaging replies",
        "actions:onsite_conversion.purchase": "Meta purchases",
        "actions:onsite_conversion.initiate_checkout": "Meta checkouts initiated",
        "actions:onsite_conversion.add_to_wishlist": "Meta adds to wishlist",
        "actions:onsite_conversion.view_content": "Meta view content",
        "actions:onsite_conversion.click_to_call": "Phone number clicks",
        "actions:onsite_conversion.find_location": "Get directions clicks",
        "conversions:contact_website": "Website contacts",
        "conversions:customize_product_website": "Website products customised",
        "conversions:donate_website": "Website donations",
        "conversions:donate_on_facebook": "Meta donations",
        "donation_roas:donate_total": "Donation ROAS (return on ad spend)",
        "donation_roas:donate_on_facebook": "Meta donation ROAS",
        "conversions:find_location_website": "Website location searches",
        "conversions:schedule_website": "Website appointments scheduled",
        "conversions:start_trial_website": "Website trials started",
        "conversions:submit_application_website": "Website applications submitted",
        "conversions:subscribe_website": "Website subscriptions",
        "conversions:recurring_subscription_payment_website": "Website recurring subscription payments",
        "conversions:cancel_subscription_website": "Website cancelled subscriptions",
        "conversions:ad_click_mobile_app": "In-app ad clicks",
        "conversions:ad_impression_mobile_app": "In-app ad impressions",
        "conversions:contact_mobile_app": "Mobile app contacts",
        "conversions:customize_product_mobile_app": "Mobile app products customised",
        "conversions:donate_mobile_app": "Mobile app donations",
        "conversions:find_location_mobile_app": "Mobile app location searches",
        "conversions:schedule_mobile_app": "Mobile app appointments scheduled",
        "conversions:start_trial_mobile_app": "Mobile app trials started",
        "conversions:submit_application_mobile_app": "Mobile app applications submitted",
        "conversions:subscribe_mobile_app": "Mobile app subscriptions",
        "conversions:recurring_subscription_payment_mobile_app": "App recurring subscription payments",
        "conversions:cancel_subscription_mobile_app": "App cancelled subscriptions",
        "conversions:contact_offline": "Offline contacts",
        "conversions:customize_product_offline": "Offline products customised",
        "conversions:donate_offline": "Offline donations",
        "conversions:find_location_offline": "Offline location searches",
        "conversions:schedule_offline": "Offline appointments scheduled",
        "conversions:start_trial_offline": "Offline trials started",
        "conversions:submit_application_offline": "Offline applications submitted",
        "conversions:submit_application_on_facebook": "Meta applications submitted",
        "conversions:subscribe_offline": "Offline subscriptions",
        "conversions:recurring_subscription_payment_offline": "Offline recurring subscription payments",
        "conversions:cancel_subscription_offline": "Offline cancelled subscriptions",
        "conversions:contact_total": "Contacts",
        "conversions:customize_product_total": "Products customised",
        "conversions:donate_total": "Donations",
        "conversions:find_location_total": "Location searches",
        "conversions:schedule_total": "Appointments scheduled",
        "conversions:start_trial_total": "Trials started",
        "conversions:submit_application_total": "Applications submitted",
        "conversions:subscribe_total": "Subscriptions",
        "conversions:recurring_subscription_payment_total": "Recurring subscription payments",
        "conversions:cancel_subscription_total": "Cancelled subscriptions",
        "conversion_values:contact_website": "Website contact conversion value",
        "conversion_values:customize_product_website": "Website product customisation conversion value",
        "conversion_values:donate_website": "Website donation conversion value",
        "conversion_values:donate_on_facebook": "Meta donate conversion value",
        "conversion_values:submit_application_on_facebook": "Meta submit application conversion value",
        "conversion_values:find_location_website": "Website find location conversion value",
        "conversion_values:schedule_website": "Website scheduling conversion value",
        "conversion_values:start_trial_website": "Website trial started conversion value",
        "conversion_values:submit_application_website": "Website application submitted conversion value",
        "conversion_values:subscribe_website": "Website subscription conversion value",
        "conversion_values:recurring_subscription_payment_website": "Website recurring subscription payment value",
        "conversion_values:cancel_subscription_website": "Website cancel subscription value",
        "conversion_values:contact_mobile_app": "Mobile app contact conversion value",
        "conversion_values:customize_product_mobile_app": "Mobile app product customisation conversion value",
        "conversion_values:donate_mobile_app": "Mobile app donation conversion value",
        "conversion_values:find_location_mobile_app": "Mobile app find location conversion value",
        "conversion_values:schedule_mobile_app": "Mobile app scheduling conversion value",
        "conversion_values:start_trial_mobile_app": "Mobile app trial started conversion value",
        "conversion_values:submit_application_mobile_app": "Mobile app application submitted conversion value",
        "conversion_values:subscribe_mobile_app": "Mobile app subscription conversion value",
        "conversion_values:recurring_subscription_payment_mobile_app": "Mobile recurring subscription payment conversion value",
        "conversion_values:cancel_subscription_mobile_app": "Mobile app cancel subscription conversion value",
        "conversion_values:contact_offline": "Offline contact conversion value",
        "conversion_values:customize_product_offline": "Offline product customised conversion value",
        "conversion_values:donate_offline": "Offline donation conversion value",
        "conversion_values:find_location_offline": "Offline find location Conversion Value",
        "conversion_values:schedule_offline": "Offline scheduling conversion value",
        "conversion_values:start_trial_offline": "Offline trial started conversion value",
        "conversion_values:submit_application_offline": "Offline application submitted conversion value",
        "conversion_values:subscribe_offline": "Offline subscription conversion value",
        "conversion_values:recurring_subscription_payment_offline": "Offline recurring subscription payment conversion value",
        "conversion_values:cancel_subscription_offline": "Offline cancel subscription conversion value",
        "conversion_values:contact_total": "Contact conversion value",
        "conversion_values:customize_product_total": "Customise Product conversion value",
        "conversion_values:donate_total": "Donate conversion value",
        "conversion_values:find_location_total": "Find location conversion value",
        "conversion_values:schedule_total": "Schedule conversion value",
        "conversion_values:start_trial_total": "Start Trial conversion value",
        "conversion_values:submit_application_total": "Submit Application conversion value",
        "conversion_values:subscribe_total": "Subscribe conversion value",
        "conversion_values:recurring_subscription_payment_total": "Recurring subscription payment conversion value",
        "conversion_values:cancel_subscription_total": "Cancel subscription conversion value",
        "cost_per_conversion:ad_click_mobile_app": "Cost per in-app ad click",
        "cost_per_conversion:ad_impression_mobile_app": "Cost per 1,000 in-app ad impressions",
        "cost_per_conversion:contact_total": "Cost per Contact",
        "cost_per_conversion:customize_product_total": "Cost per product customised",
        "cost_per_conversion:donate_total": "Cost per donation",
        "cost_per_conversion:find_location_total": "Cost per location find",
        "cost_per_conversion:schedule_total": "Cost per schedule",
        "cost_per_conversion:start_trial_total": "Cost per trial started",
        "cost_per_conversion:submit_application_total": "Cost per application submitted",
        "cost_per_conversion:subscribe_total": "Cost per subscription",
        "contact_actions:contact": "Contacts",
        "customize_product_actions:customize_product": "Products customised",
        "donate_actions:donate": "Donations",
        "find_location_actions:find_location": "Location searches",
        "schedule_actions:schedule": "Appointments scheduled",
        "start_trial_actions:start_trial": "Trials started",
        "submit_application_actions:submit_application": "Applications submitted",
        "subscribe_actions:subscribe": "Subscriptions",
        "actions:omni_add_to_cart": "Adds to cart",
        "actions:add_to_wishlist": "Adds to wishlist",
        "actions:omni_add_to_wishlist": "Adds to wishlist",
        "actions:add_payment_info": "Adds of payment info",
        "actions:lead": "Leads",
        "actions:onsite_conversion.lead_grouped": "Meta leads",
        "qualifying_question_qualify_answer_rate": "Qualified response rate",
        "actions:omni_purchase": "Purchases",
        "actions:onsite_web_purchase": "Purchases (Meta and website)",
        "actions:omni_search": "Searches",
        "actions:omni_initiated_checkout": "Checkouts initiated",
        "actions:omni_complete_registration": "Registrations completed",
        "actions:omni_view_content": "Content views",
        "actions:omni_activate_app": "App activiations",
        "actions:omni_app_install": "App Installs",
        "actions:omni_achievement_unlocked": "Achievements unlocked",
        "actions:omni_level_achieved": "Levels achieved",
        "actions:omni_rate": "Ratings submitted",
        "actions:omni_tutorial_completion": "Tutorials completed",
        "actions:omni_spend_credits": "Credit spends",
        "actions:omni_custom": "Custom events",
        "actions:other": "Other Actions",
        "actions:page_engagement": "Page engagement",
        "actions:photo_view": "Photo views",
        "actions:post": "Post shares",
        "actions:comment": "Post comments",
        "actions:post_engagement": "Post engagement",
        "actions:post_like": "Post reactions",
        "actions:post_reaction": "Post reactions",
        "actions:onsite_conversion.post_save": "Post saves",
        "actions:rsvp": "Event responses",
        "actions:click_to_call_call_confirm": "Estimated call confirmation clicks",
        "actions:click_to_call_native_call_placed": "Calls placed",
        "actions:click_to_call_native_20s_call_connect": "20-second calls",
        "actions:click_to_call_native_60s_call_connect": "60-second calls",
        "actions:click_to_call_callback_request_submitted": "Callback requests submitted",
        "actions:onsite_conversion.messaging_user_subscribed": "Messaging subscriptions",
        "actions:onsite_conversion.messaging_welcome_message_view": "Welcome message views",
        "actions:onsite_conversion.messaging_conversation_replied_7d": "Messaging conversations replied",
        "custom_derived_metrics:product_group_view": "Product group views",
        "custom_derived_metrics:product_detail_view": "Product detail views",
        "actions:onsite_conversion_messaging_order_created": "Orders created",
        "actions:onsite_conversion_orders_shipped": "Orders dispatched",
        "actions:tab_view": "Page tab views",
        "actions:video_play": "Clicks to play video",
        "actions:vote": "Question answers",
        "unique_actions:app_custom_event.fb_mobile_achievement_unlocked": "Unique mobile app achievements unlocked",
        "unique_actions:app_custom_event.fb_mobile_activate_app": "Unique mobile app sessions",
        "unique_actions:app_custom_event.fb_mobile_add_payment_info": "Unique mobile app payment info adds",
        "unique_actions:app_custom_event.fb_mobile_add_to_cart": "Unique mobile app adds to cart",
        "unique_actions:app_custom_event.fb_mobile_add_to_wishlist": "Unique mobile app adds to wishlist",
        "unique_actions:app_custom_event.fb_mobile_complete_registration": "Unique mobile app registrations completed",
        "unique_actions:app_custom_event.fb_mobile_content_view": "Unique mobile app content views",
        "unique_actions:app_custom_event.fb_mobile_d2_retention": "Unique mobile app day 2 retention",
        "unique_actions:app_custom_event.fb_mobile_d7_retention": "Unique mobile app day 7 retention",
        "unique_actions:app_custom_event.fb_mobile_initiated_checkout": "Unique mobile app checkouts initiated",
        "unique_actions:app_custom_event.fb_mobile_level_achieved": "Unique mobile app levels completed",
        "unique_actions:app_custom_event.fb_mobile_purchase": "Unique mobile app purchases",
        "unique_actions:app_custom_event.fb_mobile_rate": "Unique mobile app ratings submitted",
        "unique_actions:app_custom_event.fb_mobile_search": "Unique mobile app searches",
        "unique_actions:app_custom_event.fb_mobile_spent_credits": "Unique mobile app credits spent",
        "unique_actions:app_custom_event.fb_mobile_tutorial_completion": "Unique mobile app tutorials completed",
        "unique_actions:omni_achievement_unlocked": "Unique achievements unlocked",
        "unique_actions:omni_activate_app": "Unique app activations",
        "unique_actions:omni_level_achieved": "Unique levels completed",
        "unique_actions:omni_rate": "Unique ratings submitted",
        "unique_actions:omni_spend_credits": "Unique credit spends",
        "unique_actions:omni_tutorial_completion": "Unique tutorials completed",
        "unique_actions:add_payment_info": "Unique adds of payment info",
        "unique_actions:omni_add_to_cart": "Unique adds to cart",
        "unique_actions:add_to_wishlist": "Unique adds to wishlist",
        "unique_actions:omni_add_to_wishlist": "Unique adds to wishlist",
        "unique_actions:omni_complete_registration": "Unique registrations completed",
        "unique_actions:omni_view_content": "Unique content views",
        "unique_actions:omni_initiated_checkout": "Unique checkouts initiated",
        "unique_actions:omni_purchase": "Unique purchases",
        "unique_actions:omni_search": "Unique searches",
        "unique_actions:attention_event": "Unique Attention Impressions",
        "unique_actions:dwell": "Post dwells (people)",
        "unique_actions:landing_page_view": "Unique landing page views",
        "unique_actions:link_click": "Unique link clicks",
        "unique_actions:offsite_mobile_app_conversion": "Mobile App Unique Event",
        "action_values:app_custom_event": "Mobile app actions conversion value",
        "action_values:app_custom_event.fb_mobile_achievement_unlocked": "Mobile app achievements unlocked conversion value",
        "action_values:app_custom_event.fb_mobile_activate_app": "Mobile app sessions conversion value",
        "action_values:app_custom_event.fb_mobile_add_payment_info": "Mobile app payment info adds conversion value",
        "action_values:app_custom_event.fb_mobile_add_to_cart": "Mobile app adds to cart conversion value",
        "action_values:app_custom_event.fb_mobile_add_to_wishlist": "Mobile app adds to wishlist conversion value",
        "action_values:app_custom_event.fb_mobile_complete_registration": "Mobile app registrations completed conversion value",
        "action_values:app_custom_event.fb_mobile_content_view": "Mobile app content views conversion value",
        "action_values:app_custom_event.fb_mobile_initiated_checkout": "Mobile app checkouts initiated conversion value",
        "action_values:app_custom_event.fb_mobile_level_achieved": "Mobile app levels completed conversion value",
        "action_values:app_custom_event.fb_mobile_purchase": "Mobile app purchases conversion value",
        "action_values:app_custom_event.fb_mobile_rate": "Mobile app ratings submitted conversion value",
        "action_values:app_custom_event.fb_mobile_search": "Mobile App Searches conversion value",
        "action_values:app_custom_event.fb_mobile_spent_credits": "Mobile app credits spent conversion value",
        "action_values:app_custom_event.fb_mobile_tutorial_completion": "Mobile app tutorials completed conversion value",
        "action_values:app_custom_event.other": "Other Mobile App Actions conversion value",
        "action_values:app_engagement": "App Engagement conversion value",
        "action_values:app_install": "Desktop App Installs conversion value",
        "action_values:app_story": "App Story Engagement conversion rate",
        "action_values:app_use": "App Uses conversion value",
        "action_values:attention_event": "Attention Impressions Conversion Value",
        "action_values:checkin": "Check-ins conversion value",
        "action_values:commerce_event": "Commerce Actions Conversion Value",
        "action_values:commerce_event.add_to_cart": "Adds to Basket (Commerce) Conversion Value",
        "action_values:commerce_event.message_to_buy": "Messages to Buy (Commerce) Conversion Value",
        "action_values:commerce_event.other": "Other Commerce Actions Conversion Value",
        "action_values:commerce_event.purchase": "Commerce purchases conversion value",
        "action_values:commerce_event.view_content": "Product Views (Commerce) Conversion Value",
        "action_values:receive_offer": "Offer Claims conversion value",
        "action_values:credit_spent": "Desktop credit spends conversion value",
        "action_values:dwell": "Post Dwells conversion value",
        "action_values:follow": "Question Follows conversion value",
        "action_values:games.plays": "Game Plays conversion value",
        "action_values:gift_sale": "Gift sale conversion value",
        "action_values:like": "Page Likes conversion value",
        "action_values:link_click": "Link Clicks conversion value",
        "action_values:mention": "Page Mentions conversion value",
        "action_values:offsite_mobile_app_conversion": "Mobile App Event conversion value",
        "action_values:mobile_app_install": "Mobile App Installs conversion value",
        "action_values:new_mobile": "Newly Purchased Mobile Devices conversion value",
        "action_values:offline_conversion": "Offline Action Value (All)",
        "action_values:offline_conversion.add_payment_info": "Offline payment info adds conversion value",
        "action_values:offline_conversion.add_to_cart": "Offline adds to cart conversion value",
        "action_values:offline_conversion.add_to_wishlist": "Offline adds to wishlist conversion value",
        "action_values:offline_conversion.complete_registration": "Offline registrations completed conversion value",
        "action_values:offline_conversion.initiate_checkout": "Offline checkouts initiated conversion value",
        "action_values:offline_conversion.lead": "Offline leads conversion value",
        "action_values:offline_conversion.other": "Other offline conversion value",
        "action_values:offline_conversion.purchase": "Offline purchases conversion value",
        "action_values:offline_conversion.search": "Offline searches conversion value",
        "action_values:offline_conversion.view_content": "Offline content views conversion value",
        "action_values:offsite_conversion": "Website conversion value",
        "action_values:offsite_conversion.add_to_cart": "Website adds to cart conversion value (conversion-tracking pixel)",
        "action_values:offsite_conversion.checkout": "Website checkouts conversion value (conversion-tracking pixel)",
        "action_values:offsite_conversion.fb_pixel_add_payment_info": "Website payment info adds conversion value",
        "action_values:offsite_conversion.fb_pixel_add_to_cart": "Website adds to cart conversion value",
        "action_values:offsite_conversion.fb_pixel_add_to_wishlist": "Website adds to wishlist conversion value",
        "action_values:offsite_conversion.fb_pixel_complete_registration": "Website registrations completed conversion value",
        "action_values:offsite_conversion.fb_pixel_initiate_checkout": "Website checkouts initiated conversion value",
        "action_values:offsite_conversion.fb_pixel_lead": "Website leads conversion value",
        "action_values:offsite_conversion.fb_pixel_purchase": "Website purchases conversion value",
        "action_values:offsite_conversion.fb_pixel_search": "Website searches conversion value",
        "action_values:offsite_conversion.fb_pixel_view_content": "Website content views conversion value",
        "action_values:offsite_conversion.key_page_view": "Website key page views conversion value (conversion-tracking pixel)",
        "action_values:offsite_conversion.lead": "Website leads conversion value (conversion-tracking pixel)",
        "action_values:offsite_conversion.other": "Other website conversion value (conversion-tracking pixel)",
        "action_values:offsite_conversion.registration": "Website registrations conversion value (conversion-tracking pixel)",
        "action_values:onsite_conversion.add_to_cart": "Meta add to cart conversion value",
        "action_values:onsite_conversion.flow_complete": "Meta workflow completion conversion value",
        "action_values:onsite_conversion.message_to_buy": "Meta message to buy conversion value",
        "action_values:onsite_conversion.purchase": "Meta purchase conversion value",
        "action_values:onsite_conversion.initiate_checkout": "Meta checkouts initiated conversion value",
        "action_values:onsite_conversion.view_content": "Meta view content conversion value",
        "action_values:onsite_conversion.add_to_wishlist": "Meta adds to wishlist conversion value",
        "contact_value:contact": "Contacts conversion value",
        "customize_product_value:customize_product": "Customise Product conversion value",
        "donate_value:donate": "Donate conversion value",
        "find_location_value:find_location": "Location searches conversion value",
        "schedule_value:schedule": "Appointments scheduled conversion value",
        "start_trial_value:start_trial": "Trials started conversion value",
        "submit_application_value:submit_application": "Applications submitted conversion value",
        "subscribe_value:subscribe": "Subscriptions conversion value",
        "action_values:omni_add_to_cart": "Adds to cart conversion value",
        "action_values:add_to_wishlist": "Adds to wishlist conversion value",
        "action_values:omni_add_to_wishlist": "Adds to wishlist conversion value",
        "action_values:add_payment_info": "Adds of payment info conversion value",
        "action_values:lead": "Leads Conversion Value",
        "action_values:onsite_conversion.lead_grouped": "Meta leads conversion value",
        "action_values:omni_search": "Searches Conversion Value",
        "action_values:omni_initiated_checkout": "Checkouts initiated conversion value",
        "action_values:omni_complete_registration": "Registrations completed conversion value",
        "action_values:omni_view_content": "Content Views Conversion Value",
        "action_values:omni_purchase": "Purchases conversion value",
        "action_values:omni_activate_app": "App activations conversion value",
        "action_values:omni_achievement_unlocked": "Achievements unlocked conversion value",
        "action_values:omni_level_achieved": "Levels achieved conversion value",
        "action_values:omni_rate": "Ratings submitted conversion value",
        "action_values:omni_tutorial_completion": "Tutorials completed conversion value",
        "action_values:omni_spend_credits": "Credit spends conversion value",
        "action_values:other": "Other Actions conversion value",
        "action_values:page_engagement": "Page Engagement conversion value",
        "action_values:photo_view": "Photo Views conversion value",
        "action_values:post": "Post Shares conversion value",
        "action_values:comment": "Post Comments conversion value",
        "action_values:post_engagement": "Post Engagement conversion value",
        "action_values:post_like": "Post reactions conversion value",
        "action_values:rsvp": "Event Responses conversion value",
        "action_values:tab_view": "Page Tab Views conversion value",
        "action_values:video_play": "Clicks to Play Video conversion value",
        "action_values:video_view": "Video Views conversion value",
        "action_values:vote": "Question Answers conversion value",
        "canvas_avg_view_percentage_per_component:canvas_view": "Canvas component time percentage",
        "canvas_component_avg_pct_view:canvas_view": "Canvas component time percentage",
        "cost_per_10_sec_video_view:video_view": "Cost per 10-second video view",
        "cost_per_15_sec_video_view:video_view": "Cost per 15-second video view",
        "cost_per_thruplay:video_view": "Cost per ThruPlay",
        "cost_per_thruplay_watched_action:video_view": "Cost per ThruPlay interaction",
        "cost_per_action_type:app_custom_event": "Cost per mobile app action",
        "cost_per_action_type:app_custom_event.fb_mobile_achievement_unlocked": "Cost per mobile app achievement unlocked",
        "cost_per_action_type:app_custom_event.fb_mobile_activate_app": "Cost per mobile app session",
        "cost_per_action_type:app_custom_event.fb_mobile_add_payment_info": "Cost per mobile app payment info add",
        "cost_per_action_type:app_custom_event.fb_mobile_add_to_cart": "Cost per mobile app add to cart",
        "cost_per_action_type:app_custom_event.fb_mobile_add_to_wishlist": "Cost per mobile app add to wishlist",
        "cost_per_action_type:app_custom_event.fb_mobile_complete_registration": "Cost per mobile app registration completed",
        "cost_per_action_type:app_custom_event.fb_mobile_content_view": "Cost per mobile app content view",
        "cost_per_action_type:app_custom_event.fb_mobile_d2_retention": "Cost per mobile app day 2 retention",
        "cost_per_action_type:app_custom_event.fb_mobile_d7_retention": "Cost per mobile app day 7 retention",
        "cost_per_action_type:app_custom_event.fb_mobile_initiated_checkout": "Cost per mobile app checkout initiated",
        "cost_per_action_type:app_custom_event.fb_mobile_level_achieved": "Cost per mobile app level completed",
        "cost_per_action_type:app_custom_event.fb_mobile_purchase": "Cost per mobile app purchase",
        "cost_per_action_type:app_custom_event.fb_mobile_rate": "Cost per mobile app rating submitted",
        "cost_per_action_type:app_custom_event.fb_mobile_search": "Cost per mobile app search",
        "cost_per_action_type:app_custom_event.fb_mobile_spent_credits": "Cost per mobile app credit spent",
        "cost_per_action_type:app_custom_event.fb_mobile_tutorial_completion": "Cost per mobile app tutorial completed",
        "cost_per_action_type:app_custom_event.other": "Cost per other mobile app action",
        "cost_per_action_type:app_engagement": "Cost per desktop app engagement",
        "cost_per_action_type:app_install": "Cost per desktop app install",
        "cost_per_action_type:app_story": "Cost per desktop app story engagement",
        "cost_per_action_type:app_use": "Cost per desktop app use",
        "cost_per_action_type:attention_event": "Cost per attention impression",
        "cost_per_action_type:checkin": "Cost per check-in",
        "cost_per_action_type:commerce_event": "Cost per commerce action",
        "cost_per_action_type:commerce_event.add_to_cart": "Cost per add to cart (commerce)",
        "cost_per_action_type:commerce_event.message_to_buy": "Cost per Message to Buy (Commerce)",
        "cost_per_action_type:commerce_event.other": "Cost per other commerce action",
        "cost_per_action_type:commerce_event.purchase": "Cost per purchase (commerce)",
        "cost_per_action_type:commerce_event.view_content": "Cost per product view (commerce)",
        "cost_per_action_type:receive_offer": "Cost per offer saved",
        "cost_per_action_type:credit_spent": "Cost per desktop add credit spend action",
        "cost_per_action_type:dwell": "Cost per post dwell",
        "cost_per_action_type:follow": "Cost per question follow",
        "cost_per_action_type:games.plays": "Cost per game play",
        "cost_per_action_type:gift_sale": "Cost per gift sale",
        "cost_per_action_type:landing_page_view": "Cost per landing page view",
        "cost_per_action_type:leadgen.other": "Cost per lead (form)",
        "cost_per_action_type:leadgen_grouped": "Cost per lead (form)",
        "cost_per_action_type:link_click": "CPC (cost per link click)",
        "cost_per_action_type:mention": "Cost per Page mention",
        "cost_per_action_type:mobile_app_install": "Cost per mobile app install",
        "cost_per_action_type:new_mobile": "Cost per Newly Purchased Mobile Device",
        "cost_per_action_type:offline_conversion": "Cost per Offline Action (All)",
        "cost_per_action_type:offline_conversion.add_payment_info": "Cost per offline payment info add",
        "cost_per_action_type:offline_conversion.add_to_cart": "Cost per offline add to cart",
        "cost_per_action_type:offline_conversion.add_to_wishlist": "Cost per offline add to wishlist",
        "cost_per_action_type:offline_conversion.complete_registration": "Cost per offline registration completed",
        "cost_per_action_type:offline_conversion.initiate_checkout": "Cost per offline checkout initiated",
        "cost_per_action_type:offline_conversion.lead": "Cost per offline lead",
        "cost_per_action_type:offline_conversion.other": "Cost per other offline conversion",
        "cost_per_action_type:offline_conversion.purchase": "Cost per offline purchase",
        "cost_per_action_type:offline_conversion.search": "Cost per offline search",
        "cost_per_action_type:offline_conversion.view_content": "Cost per offline content view",
        "cost_per_action_type:offsite_conversion": "Cost per website conversion",
        "cost_per_action_type:offsite_conversion.add_to_cart": "Cost per website add to cart (conversion-tracking pixel)",
        "cost_per_action_type:offsite_conversion.checkout": "Cost per website checkout (conversion-tracking pixel)",
        "cost_per_action_type:offsite_conversion.fb_pixel_add_payment_info": "Cost per website payment info add",
        "cost_per_action_type:offsite_conversion.fb_pixel_add_to_cart": "Cost per website add to cart",
        "cost_per_action_type:offsite_conversion.fb_pixel_add_to_wishlist": "Cost per website add to wishlist",
        "cost_per_action_type:offsite_conversion.fb_pixel_complete_registration": "Cost per website registration completed",
        "cost_per_action_type:offsite_conversion.fb_pixel_initiate_checkout": "Cost per website checkout initiated",
        "cost_per_action_type:offsite_conversion.fb_pixel_lead": "Cost per website lead",
        "cost_per_action_type:offsite_conversion.fb_pixel_purchase": "Cost per website purchase",
        "cost_per_action_type:offsite_conversion.fb_pixel_search": "Cost per website search",
        "cost_per_action_type:offsite_conversion.fb_pixel_view_content": "Cost per website content views",
        "cost_per_action_type:offsite_conversion.key_page_view": "Cost per website key page view (conversion-tracking pixel)",
        "cost_per_action_type:offsite_conversion.lead": "Cost per website lead (conversion-tracking pixel)",
        "cost_per_action_type:offsite_conversion.other": "Cost per other website conversion (conversion-tracking pixel)",
        "cost_per_action_type:offsite_conversion.registration": "Cost per website registration (conversion-tracking pixel)",
        "cost_per_action_type:onsite_conversion.add_to_cart": "Cost per on-Facebook add to cart",
        "cost_per_action_type:onsite_conversion.flow_complete": "Cost per Meta workflow completion",
        "cost_per_action_type:onsite_conversion.referral_sender_invites_sent": "Cost per referral invitation",
        "cost_per_action_type:onsite_conversion.referral_sender_message_sent": "Cost per referral invitation message",
        "cost_per_action_type:onsite_conversion.messaging_first_reply": "Cost per new messaging connection",
        "cost_per_action_type:onsite_conversion.messaging_reply": "Cost per messaging reply",
        "cost_per_action_type:onsite_conversion.message_to_buy": "Cost per Meta message to buy",
        "cost_per_action_type:onsite_conversion.purchase": "Cost per Meta purchase",
        "cost_per_action_type:onsite_conversion.view_content": "Cost per Meta view content",
        "cost_per_contact:contact": "Cost per Contact",
        "cost_per_customize_product:customize_product": "Cost per product customised",
        "cost_per_donate:donate": "Cost per donation",
        "cost_per_find_location:find_location": "Cost per location find",
        "cost_per_schedule:schedule": "Cost per schedule",
        "cost_per_start_trial:start_trial": "Cost per trial started",
        "cost_per_submit_application:submit_application": "Cost per application submitted",
        "cost_per_subscribe:subscribe": "Cost per subscription",
        "cost_per_action_type:omni_add_to_cart": "Cost per add to cart",
        "cost_per_action_type:add_to_wishlist": "Cost per add to wishlist",
        "cost_per_action_type:omni_add_to_wishlist": "Cost per add to wishlist",
        "cost_per_action_type:add_payment_info": "Cost per add of payment info",
        "cost_per_action_type:lead": "Cost per Lead",
        "cost_per_action_type:omni_search": "Cost per Search",
        "cost_per_action_type:omni_initiated_checkout": "Cost per checkout initiated",
        "cost_per_action_type:omni_complete_registration": "Cost per registration completed",
        "cost_per_action_type:omni_view_content": "Cost per Content View",
        "cost_per_action_type:omni_purchase": "Cost per purchase",
        "cost_per_action_type:omni_activate_app": "Cost per app activation",
        "cost_per_action_type:omni_app_install": "Cost per App Install",
        "cost_per_action_type:omni_achievement_unlocked": "Cost per achievement unlocked",
        "cost_per_action_type:omni_level_achieved": "Cost per level achieved",
        "cost_per_action_type:omni_rate": "Cost per rating submitted",
        "cost_per_action_type:omni_tutorial_completion": "Cost per tutorial completed",
        "cost_per_action_type:omni_spend_credits": "Cost per credit spend",
        "cost_per_action_type:other": "Cost per Other Action",
        "cost_per_action_type:omni_custom": "Cost per custom event",
        "cost_per_action_type:page_engagement": "Cost per Page engagement",
        "cost_per_action_type:photo_view": "Cost per photo view",
        "cost_per_action_type:post": "Cost per post share",
        "cost_per_action_type:comment": "Cost per post comment",
        "cost_per_action_type:post_engagement": "Cost per post engagement",
        "cost_per_action_type:post_like": "Cost per post reaction",
        "cost_per_action_type:post_reaction": "Cost per post reaction",
        "cost_per_action_type:onsite_conversion.post_save": "Cost per post save",
        "cost_per_action_type:rsvp": "Cost per event response",
        "cost_per_action_type:tab_view": "Cost per Page tab view",
        "cost_per_action_type:video_play": "Cost per click to play video",
        "cost_per_action_type:vote": "Cost per question answer",
        "cost_per_outbound_click:outbound_click": "Cost per outbound click",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_achievement_unlocked": "Cost per unique mobile app achievement unlocked",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_activate_app": "Cost per unique mobile app session",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_add_payment_info": "Cost per unique mobile app payment info add",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_add_to_cart": "Cost per unique mobile app add to cart",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_add_to_wishlist": "Cost per unique mobile app add to wishlist",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_complete_registration": "Cost per unique mobile app registration completed",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_content_view": "Cost per unique mobile app content view",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_d2_retention": "Cost per unique mobile app day 2 retention",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_d7_retention": "Cost per unique mobile app day 7 retention",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_initiated_checkout": "Cost per unique mobile app checkout initiated",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_level_achieved": "Cost per unique mobile app level completed",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_purchase": "Cost per unique mobile app purchase",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_rate": "Cost per unique mobile app rating submitted",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_search": "Cost per unique mobile app search",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_spent_credits": "Cost per unique mobile app credit spent",
        "cost_per_unique_action_type:app_custom_event.fb_mobile_tutorial_completion": "Cost per unique mobile app tutorial completed",
        "cost_per_unique_action_type:omni_achievement_unlocked": "Cost per unique achievement unlocked",
        "cost_per_unique_action_type:omni_activate_app": "Cost per unique app activation",
        "cost_per_unique_action_type:add_payment_info": "Cost per unique add of payment info",
        "cost_per_unique_action_type:omni_add_to_cart": "Cost per unique add to cart",
        "cost_per_unique_action_type:add_to_wishlist": "Cost per unique add to wishlist",
        "cost_per_unique_action_type:omni_add_to_wishlist": "Cost per unique add to wishlist",
        "cost_per_unique_action_type:omni_complete_registration": "Cost per unique registration completed",
        "cost_per_unique_action_type:omni_view_content": "Cost per unique content view",
        "cost_per_unique_action_type:omni_initiated_checkout": "Cost per unique checkout initiated",
        "cost_per_unique_action_type:omni_level_achieved": "Cost per unique level completed",
        "cost_per_unique_action_type:omni_purchase": "Cost per unique purchase",
        "cost_per_unique_action_type:omni_rate": "Cost per unique rating submitted",
        "cost_per_unique_action_type:omni_search": "Cost per unique search",
        "cost_per_unique_action_type:omni_spend_credits": "Cost per unique credit spend",
        "cost_per_unique_action_type:omni_tutorial_completion": "Cost per unique tutorial completed",
        "cost_per_unique_action_type:attention_event": "Cost per unique attention impression",
        "cost_per_unique_action_type:landing_page_view": "Cost per unique landing page view",
        "cost_per_unique_action_type:link_click": "Cost per unique link click",
        "cost_per_unique_outbound_click:outbound_click": "Cost per unique outbound click",
        "mobile_app_purchase_roas:app_custom_event.fb_mobile_purchase": "Mobile app purchase ROAS (return on advertising spend)",
        "purchase_roas:omni_purchase": "Purchase ROAS (return on ad spend)",
        "outbound_clicks:outbound_click": "Outbound clicks",
        "outbound_clicks_ctr:outbound_click": "Outbound CTR (click-through rate)",
        "unique_outbound_clicks:outbound_click": "Unique outbound clicks",
        "unique_outbound_clicks_ctr:outbound_click": "Unique outbound CTR (click-through rate)",
        "unique_video_view_10_sec:video_view": "Unique 10-second video views",
        "unique_video_view_15_sec:video_view": "Unique 15-second video views",
        "video_10_sec_watched_actions:video_view": "10-second video views",
        "video_15_sec_watched_actions:video_view": "15-second video views",
        "video_thruplay_watched_actions:video_view": "ThruPlays",
        "thruplay_watched_actions:video_view": "ThruPlay interactions",
        "store_visit_actions:store_visit": "Store Visits",
        "video_30_sec_watched_actions:video_view": "30-second video views",
        "video_play_retention_curve_actions:video_view": "Video retention curve",
        "video_completed_view_or_15s_passed_actions:video_view": "Completed view or 15 secs passed",
        "cost_per_store_visit_action:store_visit": "Cost per Store Visit",
        "video_avg_pct_watched_actions:video_view": "Avg % of video viewed",
        "video_avg_percent_watched_actions:video_view": "Video percentage watched",
        "video_avg_sec_watched_actions:video_view": "Avg duration of video viewed",
        "video_time_watched_actions:video_view": "Video total watch time",
        "video_play_actions:video_view": "Video plays",
        "video_complete_watched_actions:video_view": "30-second video views",
        "website_ctr:link_click": "CTR (link click-through rate)",
        "website_purchase_roas:offsite_conversion.fb_pixel_purchase": "Website purchase ROAS (return on advertising spend)",
        "relevance_score:negative_feedback": "Negative feedback",
        "relevance_score:organic_rank": "Organic rank",
        "relevance_score:positive_feedback": "Positive feedback",
        "relevance_score:score": "Relevance score",
        "relevance_score:status": "Relevance score status",
        "store_visits:point_estimate": "Store visits (best estimation)",
        "age_targeting": "Age (ad set settings)",
        "app_tracking_event": "App event",
        "body": "Body (ad settings)",
        "budget_remaining": "Budget Remaining",
        "custom_audiences": "Included Custom Audiences",
        "created_time": "Date created",
        "updated_time": "Date last edited",
        "destination": "Destination",
        "end_time": "Ends",
        "excluded_custom_audiences": "Excluded Custom Audiences",
        "gender_targeting": "Gender (ad set settings)",
        "labels": "Tags",
        "link_url": "Link (ad settings)",
        "location": "Location (ad set settings)",
        "offline_tracking_event": "Offline event",
        "preview_link": "Preview link",
        "related_page": "Page name",
        "spend_limit": "Campaign spending limit",
        "spent_percent": "Amount spent percentage",
        "split_test_split": "Split",
        "split_test_variable": "Variable",
        "start_time_pe": "Starts",
        "elapsed": "Time elapsed percentage",
        "title": "Headline (ad settings)",
        "website_url": "Website URL",
        "url_tags": "URL parameters",
        "conversion_tracking_pixel": "Meta pixel",
        "optimization_results_conversion_window": "Optimisation event conversion window",
        "optimization_results_indicator": "Optimisation event indicator",
        "action_target_id": "Target ID",
        "action_target_name": "Destination",
        "action_video_sound": "Video sound",
        "adgroup_objective": "Ad objective",
        "campaign_group_ui_status": "Campaign Status Code",
        "campaign_group_ui_status_name": "Campaign Status",
        "campaign_ui_status": "Ad set status code",
        "campaign_ui_status_name": "Ad set Status",
        "cost_per_action_type": "Cost per action type",
        "cost_per_unique_action_type": "Cost per unique action type",
        "social_spend": "Social spending",
        "time_start": "Time Start",
        "time_stop": "Time Stop",
        "description": "Description",
        "image_hash": "Image hash",
        "video_id": "Video ID",
        "image_name": "Image name",
        "video_name": "Video name",
        "page_id": "Page ID",
        "page_name": "Page name",
        "actions:onsite_conversion.messaging_conversation_started_7d": "Messaging conversations started",
        "cost_per_action_type:onsite_conversion.messaging_conversation_started_7d": "Cost per messaging conversations started",
        "cost_per_action_type:onsite_conversion.messaging_user_subscribed": "Cost per messaging subscription",
        "interactive_component_tap": "Interactive sticker responses",
        "ar_effect_share:ar_effect_share": "Effect share",
        "instant_experience_clicks_to_open": "Instant Experience clicks to open",
        "instant_experience_clicks_to_start": "Instant Experience clicks to start",
        "instant_experience_element_impressions:instant_experience_element_impression": "Instant Experience impressions",
        "instant_experience_element_reach:instant_experience_element_impression": "Instant Experience reach",
        "instant_experience_outbound_clicks:outbound_click": "Instant Experience outbound clicks",
        "catalog_match:offsite_conversion": "Event for item matching",
        "action_brand_name": "Brand",
        "action_category_name": "Category",
        "user_segment_key": "Audience type",
        "post_conversion_signal_result": "Post-conversion results",
        "cost_per_post_conversion_signal": "Cost per post-conversion result",
        "conversion_values:ad_impression_mobile_app": "In-app ad impressions value",
        "instagram_upcoming_event_reminders_set": "Reminders on",
        "visit_instagram_profile": "Instagram profile visits",
        "onsite_conversion_messaging_order_created": "Orders created",
        "onsite_conversion_orders_shipped": "Orders dispatched",
        "cpas_purchase_conversion_value_online": "Purchases conversion value",
        "cpas_purchases_online": "Purchases",
        "cpas_purchases_conversion_value_shared_online": "Purchases conversion value for shared items",
        "cpas_link_clicks_online": "Link clicks",
        "cpas_amount_spent_online": "Amount spent",
        "cpas_adds_to_cart_online": "Adds to cart",
        "cpas_purchase_roas_shared_online": "Purchase ROAS for shared items",
        "cpas_purchase_conversion_value_mpa": "Purchases conversion value",
        "cpas_purchase_roas_mpa": "Purchase ROAS",
        "cpas_purchases_conversion_value_shared_mpa": "Purchases conversion value for shared items",
        "cpas_link_clicks_mpa": "Link clicks",
        "cpas_amount_spent_mpa": "Amount spent",
        "cpas_purchases_with_shared_items_mpa": "Purchases with shared items",
        "cpas_purchase_roas_shared_mpa": "Purchase ROAS for shared items",
        "cpas_purchases_mpa": "Purchases"
    }
}
